version: '3.7'
services:
  postgres:
    image: postgres:alpine3.19
    restart: always
    environment:
      - POSTGRES_DB=pgsql-saas
      - POSTGRES_USER=pgsql-saas
      - POSTGRES_PASSWORD=pgsql-saas
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"

volumes:
  postgres_data: